version: '3.8'

services:
  db:
    image: postgres:14-alpine
    container_name: hanaloop_db
    restart: always
    environment:
      POSTGRES_USER: johndoe
      POSTGRES_PASSWORD: randompassword
      POSTGRES_DB: hanaloop
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: hanaloop_app
    restart: always
    ports:
      - "3000:3000"
    environment:
      DATABASE_URL: postgresql://johndoe:randompassword@db:5432/hanaloop?schema=public
      NODE_ENV: production
    depends_on:
      - db

volumes:
  postgres_data:
